### PR TITLE
Add Node.js 12 to Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks for adding this!

All the Lambda functions still run on the 10.x runtime but I’m looking forward to a runtime upgrade soon.

Would you like to help with that as well? It might be part of this PR, if there aren’t major complications (there shouldn’t be!).

**Comment by gliptak** [comment]
@alexcasalboni certainly. please provide some pointers

**Comment by alexcasalboni** [comment]
https://github.com/alexcasalboni/aws-lambda-power-tuning/commit/67d6220ac844aae56144242dcf440b9222f70f88 is the upgrade from `8.10` to `10.x` :)

The new runtime code is `nodejs12.x`, so this should be straightforward and the code shouldn't require changes since tests are already [succeeding](https://travis-ci.com/alexcasalboni/aws-lambda-power-tuning/jobs/281483480).

**Comment by alexcasalboni** [comment]
Thank you again @gliptak 🙏

**Pull request merged**
