### PR TITLE
update readme to show deploying with cdk

### PR DESCRIPTION
**Pull request by nideveloper**
I have added into the readme the quickest way to deploy the power tuning state machine with AWS CDK.

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks @nideveloper 🎉 💯 

My two cents: in addition to the details about the CDK itself and the instructions to use cdk-patterns, I'd also add the 10 lines required to include Lambda Power Tuning in your project. 

I mean these lines:

```typescript

    new sam.CfnApplication(this, 'powerTuner', {
      location: {
        applicationId: 'arn:aws:serverlessrepo:us-east-1:451282441545:applications/aws-lambda-power-tuning',
        semanticVersion: '3.2.4'
      },
      parameters: {
        "lambdaResource": lambdaResource,
        "PowerValues": powerValues
      }
    })

```

I think this is useful because many people already have an existing CDK stack (with their Lambda functions, etc.) and maybe they just want to copy-n-paste these 10 lines there, rather than downloading the pattern and creating a brand new stack.

**Comment by nideveloper** [comment]
Agreed, that makes sense. I didn't want to only include the 10 lines because there are all the steps like which CDK modules you need installed etc but the combination of the two gives you a reference implementation as well as just the snippet for copy/pasting.

I will make that update now

**Comment by nideveloper** [comment]
I added the snippet in as the first choice and cdk patterns as the fallback cdk option in the instructions.

**Comment by alexcasalboni** [comment]
Super! Thanks for the quick edits 🙏 

Merging now!

**Pull request merged**
