### PR TITLE
Result set show cost and duration

### PR DESCRIPTION
**Pull request by hscheib**
I have been using and enjoy the tool and cost is a big consideration when picking a POWER for lambda, but SLA's are also important, so I wanted to display both cost and duration in the results. The finalizer still orders and suggests the result from price only.

### CODE REVIEW

**Comment by hscheib** [comment]
I feel dirty submitting the PR with the whitespace changes. Maybe add a npm run beatify to solve this? Wanted to get your take

**Comment by alexcasalboni** [comment]
Thanks for contributing, @hscheib! 🎉 

You are right about the whitespace changes, but don't worry. My bad for not fixing it earlier.

Your changes look good to me, but technically it's a breaking change and I have the feeling we might break existing CI/CD pipelines that somehow rely on the current output format.

How do you feel about keeping the current `cost` output and mark it as deprecated? This way we don't break anything and we still provide additional information about execution time.

Something as simple as

```js
{
    'power': ...,
    'cost': ...,  // deprecated
    'stats': { ... }
}
```

**Comment by hscheib** [comment]
Good point on the breaking change piece. I updated the README too. How does that look?

**Comment by hscheib** [comment]
I am going to remove stats field

Leave cost field

Add duration field.

Then there is no deprecation, just a new stat :)

**Comment by alexcasalboni** [comment]
Looking great, even better :)

Thank you again for contributing! 🎉🎉

**Pull request merged**
