### PR TITLE
Implement regional base price selection for AWS Step Functions

### PR DESCRIPTION
**Pull request by gino247**
Hi,

Addressing #80 
Changes to calculate price for step function use.
Using env containing the price.
Hope this is inline with what was discussed.

Regards,
Eugene

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks, @gino247 🙏 

Don't worry about the commit `introduce test-suite sinon`, I'll merge this PR after #79.

Anyways.. because 11 out of the 22 SF base prices are the same ($0.000025), maybe we can adopt the same `default` mechanism we used for Lambda's base price?

So this would be the env var: 

```json
{"default": 0.000025,"us-gov-west-1": 0.00003,"ap-northeast-2": 0.0000271,"eu-south-1": 0.00002625,"af-south-1": 0.00002975,"us-west-1": 0.0000279,"eu-west-3": 0.0000297,"ap-east-1": 0.0000275,"me-south-1": 0.0000275,"ap-south-1": 0.0000285,"us-gov-east-1": 0.00003,"sa-east-1": 0.0000375}
```

**Comment by gino247** [comment]
Change made.
Using the same logical process for both now.

Regards,
Eugene

**Comment by alexcasalboni** [comment]
Super 💯  Thanks!

I'll try to merge asap this week :)

**Comment by alexcasalboni** [comment]
Thanks again @gino247, great work 🙏  

Merging this PR now 🎉

**Pull request merged**
