### PR TITLE
add ability to customize the prefix of the statemachine name

### PR DESCRIPTION
**Pull request by TonySherman**
This will address #220, allowing customized prefixes for the StateMachine name. 

It is defaulted to the original name `powerTuningStateMachine` but the appended id will be slightly longer.

Current default: `powerTuningStateMachine-8WZnCEWFsLBW`

This PR changes the default to: `powerTuningStateMachine-7c304ce0-a4ff-11ee-89b2-0ea1c2170c63`

and allows the customized prefix: `myCustomPrefix-7c304ce0-a4ff-11ee-89b2-0ea1c2170c63`

### CODE REVIEW

**Comment by TonySherman** [comment]
Just drafting a PR to see what you think of the implementation. Have not addressed the Terraform changes yet.

**Comment by TonySherman** [comment]
I am not real familiar with Terraform but it looks like we could actually have a similar functionality by giving the statemachine a [name_prefix](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine#name_prefix) instead of `name`

If that's the case, I think we just need to update this [line](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/terraform/module/state_machine.tf#L3)

**Comment by alexcasalboni** [comment]
Thanks @TonySherman, this looks great 🚀 

@ldcorentin any chance you can share your feedback on the Terraform side of things? 😄

**Comment by TonySherman** [comment]
> @TonySherman I have added `MaxLength` to make sure the 44 chars limit is applied.
> 
> I would also play with `AllowedPattern` to make sure that we avoid restricted characters.
> 
> As for the documentation ([here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-statemachinename)):
> 
> ```
> A name must not contain:
> - white space
> - brackets < > { } [ ]
> - wildcard characters ? *
> - special characters " # % \ ^ | ~ ` $ & , ; : /
> - control characters (U+0000-001F, U+007F-009F)
> ```

I think the regex pattern I added should meet those requirements by limiting to alphanumeric characters.

**Comment by alexcasalboni** [comment]
Also, I've realized we only have 43 characters for the prefix (not 44), since we're using one for the `-` delimiter :)

**Pull request merged**
